name: CI

on:
  push:
    branches:
      - master
      - 'v2-release' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: '16.x'
      - name: install dependencies
        run: yarn
      - name: test
        run: yarn test